import { NextResponse } from "next/server";
import { Composio } from "@composio/core";

let composioInstance: any = null;

function getComposio() {
  if (composioInstance) return composioInstance;
  
  if (!process.env.COMPOSIO_API_KEY) {
    throw new Error("COMPOSIO_API_KEY is missing");
  }

  composioInstance = new Composio({
    apiKey: process.env.COMPOSIO_API_KEY,
  });
  
  return composioInstance;
}

const ALL_TOOLKITS = [
  { id: "openai", name: "OpenAI", category: "AI", description: "Advanced language models and AI tools." },
  { id: "gmail", name: "Gmail", category: "Communication", description: "Read and draft emails for notifications, summaries, and automated replies." },
  { id: "slack", name: "Slack", category: "Communication", description: "Send messages, manage channels, and automate team notifications." },
  { id: "github", name: "GitHub", category: "Development", description: "Manage repositories, issues, and pull requests with AI." },
  { id: "notion", name: "Notion", category: "Productivity", description: "Read and update pages, databases, and workspace documentation." },
  { id: "googlesheets", name: "Google Sheets", category: "Productivity", description: "Create and update spreadsheets for data tracking and reporting." },
  { id: "shopify", name: "Shopify", category: "E-Commerce", description: "Automate store management and order processing." },
  { id: "googledrive", name: "Google Drive", category: "Storage", description: "Manage files and cloud storage access." },
  { id: "supabase", name: "Supabase", category: "Database", description: "Backend-as-a-service with database and auth." },
  { id: "hubspot", name: "HubSpot", category: "CRM", description: "Manage CRM contacts, leads, and sales pipelines." },
  { id: "21risk", name: "21risk", category: "Compliance" },
  { id: "2chat", name: "2chat", category: "Communication" },
  { id: "ably", name: "Ably", category: "Communication" },
  { id: "abstract", name: "Abstract", category: "Utilities" },
  { id: "abuselpdb", name: "AbuseIPDB", category: "Security" },
  { id: "abyssale", name: "Abyssale", category: "Creative" },
  { id: "accelo", name: "Accelo", category: "Project Management" },
  { id: "accredible", name: "Accredible Certificates", category: "Education" },
  { id: "acculynx", name: "AccuLynx", category: "CRM" },
  { id: "activecampaign", name: "Active Campaign", category: "Marketing" },
  { id: "addresszen", name: "AddressZen", category: "Utilities" },
  { id: "adobe", name: "Adobe", category: "Creative" },
  { id: "adrapid", name: "Adrapid", category: "Marketing" },
  { id: "adyntel", name: "Adyntel", category: "Marketing" },
  { id: "aeroworkflow", name: "Aero Workflow", category: "Project Management" },
  { id: "aeroleads", name: "Aeroleads", category: "Sales" },
  { id: "affinda", name: "Affinda", category: "AI" },
  { id: "affinity", name: "Affinity", category: "CRM" },
  { id: "agencyzoom", name: "AgencyZoom", category: "Insurance" },
  { id: "agentmail", name: "Agent Mail", category: "AI" },
  { id: "agentql", name: "AgentQL", category: "AI" },
  { id: "agenty", name: "Agenty", category: "Automation" },
  { id: "agiled", name: "Agiled", category: "Project Management" },
  { id: "agilitycms", name: "Agility CMS", category: "CMS" },
  { id: "ahrefs", name: "Ahrefs", category: "SEO" },
  { id: "aimlapi", name: "AI ML API", category: "AI" },
  { id: "airtable", name: "Airtable", category: "Database" },
  { id: "aivoov", name: "AiVOOV", category: "AI" },
  { id: "alchemy", name: "Alchemy", category: "Blockchain" },
  { id: "algodocs", name: "Algodocs", category: "AI" },
  { id: "algolia", name: "Algolia", category: "Search" },
  { id: "allimagesai", name: "All Images AI", category: "AI" },
  { id: "alphavantage", name: "Alpha Vantage", category: "Finance" },
  { id: "altoviz", name: "Altoviz", category: "Finance" },
  { id: "alttextai", name: "AltText AI", category: "AI" },
  { id: "amara", name: "Amara", category: "Media" },
  { id: "amazon", name: "Amazon", category: "E-Commerce" },
  { id: "ambee", name: "Ambee", category: "Data" },
  { id: "ambientweather", name: "Ambient Weather", category: "Data" },
  { id: "amcards", name: "AMCards", category: "Marketing" },
  { id: "amplitude", name: "Amplitude", category: "Analytics" },
  { id: "anchorbrowser", name: "Anchor Browser", category: "Automation" },
  { id: "anonyflow", name: "AnonyFlow", category: "Privacy" },
  { id: "anthropicadmin", name: "Anthropic Administrator", category: "AI" },
  { id: "apaleo", name: "Apaleo", category: "Hospitality" },
  { id: "apex27", name: "Apex27", category: "Real Estate" },
  { id: "apibible", name: "API Bible", category: "Data" },
  { id: "apilabz", name: "API Labz", category: "AI" },
  { id: "apininjas", name: "API Ninjas", category: "Utilities" },
  { id: "apisports", name: "API Sports", category: "Sports" },
  { id: "api2pdf", name: "Api2pdf", category: "Document" },
  { id: "apiflash", name: "ApiFlash", category: "Utilities" },
  { id: "apify", name: "Apify", category: "Automation" },
  { id: "apilio", name: "Apilio", category: "Smart Home" },
  { id: "apipieai", name: "APIpie AI", category: "AI" },
  { id: "apitemplateio", name: "APITemplate.io", category: "Document" },
  { id: "apiverve", name: "APIVerve", category: "Utilities" },
  { id: "apollo", name: "Apollo", category: "Sales" },
  { id: "appcircle", name: "Appcircle", category: "Development" },
  { id: "appdrag", name: "AppDrag", category: "Development" },
  { id: "appointo", name: "Appointo", category: "Scheduling" },
  { id: "appsflyer", name: "AppsFlyer", category: "Analytics" },
  { id: "appveyor", name: "AppVeyor", category: "Development" },
  { id: "aryn", name: "Aryn", category: "AI" },
  { id: "asana", name: "Asana", category: "Project Management" },
  { id: "ascora", name: "Ascora", category: "Field Service" },
  { id: "ashby", name: "Ashby", category: "HR" },
  { id: "asindataapi", name: "ASIN Data API", category: "E-Commerce" },
  { id: "asticaai", name: "Astica AI", category: "AI" },
  { id: "asyncinterview", name: "Async Interview", category: "HR" },
  { id: "atlassian", name: "Atlassian", category: "Development" },
  { id: "attio", name: "Attio", category: "CRM" },
  { id: "auth0", name: "Auth0", category: "Security" },
  { id: "autobound", name: "Autobound", category: "Sales" },
  { id: "autom", name: "Autom", category: "Search" },
  { id: "axonaut", name: "Axonaut", category: "CRM" },
  { id: "ayrshare", name: "Ayrshare", category: "Social Media" },
  { id: "backendless", name: "Backendless", category: "Development" },
  { id: "bamboohr", name: "BambooHR", category: "HR" },
  { id: "bannerbear", name: "Bannerbear", category: "Creative" },
  { id: "bart", name: "BART", category: "Transportation" },
  { id: "basecamp", name: "Basecamp", category: "Project Management" },
  { id: "baselinker", name: "BaseLinker", category: "E-Commerce" },
  { id: "baserow", name: "Baserow", category: "Database" },
  { id: "basin", name: "Basin", category: "Forms" },
  { id: "battlenet", name: "Battle.net", category: "Gaming" },
  { id: "beaconchain", name: "Beaconchain", category: "Blockchain" },
  { id: "beaconstac", name: "Beaconstac", category: "Marketing" },
  { id: "beamer", name: "Beamer", category: "Communication" },
  { id: "beeminder", name: "Beeminder", category: "Productivity" },
  { id: "bench", name: "Bench", category: "Utilities" },
  { id: "benchmarkemail", name: "Benchmark Email", category: "Marketing" },
  { id: "benzinga", name: "Benzinga", category: "Finance" },
  { id: "bestbuy", name: "Best Buy", category: "E-Commerce" },
  { id: "betterproposals", name: "Better Proposals", category: "Sales" },
  { id: "betterstack", name: "Better Stack", category: "Development" },
  { id: "bidsketch", name: "Bidsketch", category: "Sales" },
  { id: "bigdatacloud", name: "Big Data Cloud", category: "Data" },
  { id: "bigmailer", name: "BigMailer", category: "Marketing" },
  { id: "bigml", name: "BigML", category: "AI" },
  { id: "bigpictureio", name: "BigPicture.io", category: "Data" },
  { id: "bitbucket", name: "Bitbucket", category: "Development" },
  { id: "bitquery", name: "Bitquery", category: "Blockchain" },
  { id: "bitwarden", name: "Bitwarden", category: "Security" },
  { id: "blackbaud", name: "Blackbaud", category: "Nonprofit" },
  { id: "blackboard", name: "Blackboard", category: "Education" },
  { id: "blazemeter", name: "BlazeMeter", category: "Development" },
  { id: "blocknative", name: "Blocknative", category: "Blockchain" },
  { id: "boldsign", name: "BoldSign", category: "Document" },
  { id: "bolna", name: "Bolna", category: "AI" },
  { id: "boloforms", name: "BoloForms", category: "Document" },
  { id: "boltiot", name: "Bolt IoT", category: "IoT" },
  { id: "bonsai", name: "Bonsai", category: "Finance" },
  { id: "bookingmood", name: "Bookingmood", category: "Scheduling" },
  { id: "booqable", name: "Booqable", category: "Rental" },
  { id: "borneo", name: "Borneo", category: "Security" },
  { id: "botbaba", name: "Botbaba", category: "AI" },
  { id: "botpress", name: "Botpress", category: "AI" },
  { id: "botsonic", name: "Botsonic", category: "AI" },
  { id: "botstar", name: "BotStar", category: "AI" },
  { id: "bouncer", name: "Bouncer", category: "Email" },
  { id: "box", name: "Box", category: "Storage" },
  { id: "boxhero", name: "BoxHero", category: "Inventory" },
  { id: "braintree", name: "Braintree", category: "Payments" },
  { id: "brandfetch", name: "Brandfetch", category: "Data" },
  { id: "breathehr", name: "BreatheHR", category: "HR" },
  { id: "breeze", name: "Breeze", category: "Project Management" },
  { id: "breezyhr", name: "Breezy HR", category: "HR" },
  { id: "brevo", name: "Brevo", category: "Marketing" },
  { id: "brex", name: "Brex", category: "Finance" },
  { id: "brightdata", name: "Bright Data", category: "Data" },
  { id: "brightpearl", name: "Brightpearl", category: "E-Commerce" },
  { id: "brilliantdirectories", name: "Brilliant Directories", category: "CMS" },
  { id: "browseai", name: "Browse.ai", category: "Automation" },
  { id: "browsertool", name: "Browser Tool", category: "Automation" },
  { id: "browserbase", name: "Browserbase", category: "Automation" },
  { id: "browserhub", name: "Browserhub", category: "Automation" },
  { id: "browserless", name: "Browserless", category: "Automation" },
  { id: "btcpayserver", name: "BTCPay Server", category: "Payments" },
  { id: "bubble", name: "Bubble", category: "Development" },
  { id: "bugbug", name: "Bugbug", category: "Development" },
  { id: "bugherd", name: "BugHerd", category: "Development" },
  { id: "bugsnag", name: "Bugsnag", category: "Development" },
  { id: "buildkite", name: "Buildkite", category: "Development" },
  { id: "builtwith", name: "BuiltWith", category: "Data" },
  { id: "bunnycdn", name: "BunnyCDN", category: "Infrastructure" },
  { id: "byteforms", name: "Byteforms", category: "Forms" },
  { id: "cabinpanda", name: "CabinPanda", category: "Data" },
  { id: "cal", name: "Cal", category: "Scheduling" },
  { id: "calendarhero", name: "CalendarHero", category: "Scheduling" },
  { id: "calendly", name: "Calendly", category: "Scheduling" },
  { id: "callerapi", name: "CallerAPI", category: "Communication" },
  { id: "callingly", name: "Callingly", category: "Sales" },
  { id: "callpage", name: "CallPage", category: "Sales" },
  { id: "campaigncleaner", name: "Campaign Cleaner", category: "Marketing" },
  { id: "campayn", name: "Campayn", category: "Marketing" },
  { id: "canny", name: "Canny", category: "Product" },
  { id: "canva", name: "Canva", category: "Creative" },
  { id: "canvas", name: "Canvas", category: "Education" },
  { id: "capsulecrm", name: "Capsule CRM", category: "CRM" },
  { id: "carbone", name: "Carbone", category: "Document" },
  { id: "cardly", name: "Cardly", category: "Marketing" },
  { id: "castingwords", name: "CastingWords", category: "Media" },
  { id: "cats", name: "Cats", category: "Data" },
  { id: "cdrplatform", name: "CDR Platform", category: "Sustainability" },
  { id: "censusbureau", name: "Census Bureau", category: "Data" },
  { id: "centralstationcrm", name: "CentralStationCRM", category: "CRM" },
  { id: "certifier", name: "Certifier", category: "Education" },
  { id: "chaser", name: "Chaser", category: "Finance" },
  { id: "chatbotkit", name: "ChatBotKit", category: "AI" },
  { id: "chatfai", name: "ChatFAI", category: "AI" },
  { id: "chatwork", name: "Chatwork", category: "Communication" },
  { id: "chmeetings", name: "ChMeetings", category: "Nonprofit" },
  { id: "cincopa", name: "Cincopa", category: "Media" },
  { id: "circleci", name: "CircleCI", category: "Development" },
  { id: "claidai", name: "Claid AI", category: "AI" },
  { id: "classmarker", name: "ClassMarker", category: "Education" },
  { id: "clearout", name: "Clearout", category: "Email" },
  { id: "clickhouse", name: "ClickHouse", category: "Database" },
  { id: "clickmeeting", name: "ClickMeeting", category: "Communication" },
  { id: "clickup", name: "ClickUp", category: "Project Management" },
  { id: "clockify", name: "Clockify", category: "Time Tracking" },
  { id: "close", name: "Close", category: "CRM" },
  { id: "cloudcart", name: "CloudCart", category: "E-Commerce" },
  { id: "cloudconvert", name: "CloudConvert", category: "Utilities" },
  { id: "cloudflare", name: "Cloudflare", category: "Infrastructure" },
  { id: "cloudinary", name: "Cloudinary", category: "Media" },
  { id: "cloudlayer", name: "Cloudlayer", category: "Document" },
  { id: "cloudpress", name: "Cloudpress", category: "CMS" },
  { id: "coassemble", name: "Coassemble", category: "Education" },
  { id: "coda", name: "Coda", category: "Productivity" },
  { id: "codacy", name: "Codacy", category: "Development" },
  { id: "codeinterpreter", name: "Code Interpreter", category: "Development" },
  { id: "codereadr", name: "CodeREADr", category: "Data" },
  { id: "coinbase", name: "Coinbase", category: "Blockchain" },
  { id: "coinmarketcal", name: "CoinMarketCal", category: "Blockchain" },
  { id: "coinmarketcap", name: "CoinMarketCap", category: "Blockchain" },
  { id: "coinranking", name: "Coinranking", category: "Blockchain" },
  { id: "collegefootballdata", name: "College Football Data", category: "Sports" },
  { id: "composio", name: "Composio", category: "Automation" },
  { id: "composiosearch", name: "Composio Search", category: "Search" },
  { id: "confluence", name: "Confluence", category: "Productivity" },
  { id: "connecteam", name: "Connecteam", category: "HR" },
  { id: "contentful", name: "Contentful", category: "CMS" },
  { id: "controld", name: "Control D", category: "Security" },
  { id: "conversiontools", name: "Conversion Tools", category: "Utilities" },
  { id: "convertapi", name: "ConvertAPI", category: "Utilities" },
  { id: "conveyor", name: "Conveyor", category: "Security" },
  { id: "convoloai", name: "Convolo AI", category: "AI" },
  { id: "corrently", name: "Corrently", category: "Energy" },
  { id: "countdownapi", name: "Countdown API", category: "E-Commerce" },
  { id: "coupa", name: "Coupa", category: "Finance" },
  { id: "craftmypdf", name: "CraftMyPDF", category: "Document" },
  { id: "crowdin", name: "Crowdin", category: "Localization" },
  { id: "crustdata", name: "Crustdata", category: "Data" },
  { id: "cults", name: "Cults", category: "3D Printing" },
  { id: "curated", name: "Curated", category: "Marketing" },
  { id: "currentsapi", name: "Currents API", category: "News" },
  { id: "customerio", name: "Customer.io", category: "Marketing" },
  { id: "customgpt", name: "CustomGPT", category: "AI" },
  { id: "customjs", name: "CustomJS", category: "Development" },
  { id: "cuttly", name: "Cutt.ly", category: "Utilities" },
  { id: "d2lbrightspace", name: "D2L Brightspace", category: "Education" },
  { id: "dadataru", name: "DaData.ru", category: "Data" },
  { id: "daffy", name: "Daffy", category: "Nonprofit" },
  { id: "dailybot", name: "DailyBot", category: "Productivity" },
  { id: "datadog", name: "Datadog", category: "Development" },
  { id: "datagma", name: "Datagma", category: "Data" },
  { id: "datarobot", name: "DataRobot", category: "AI" },
  { id: "deadlinefunnel", name: "Deadline Funnel", category: "Marketing" },
  { id: "deel", name: "Deel", category: "HR" },
  { id: "deepgram", name: "Deepgram", category: "AI" },
  { id: "demio", name: "Demio", category: "Marketing" },
  { id: "desktime", name: "DeskTime", category: "Time Tracking" },
  { id: "detrack", name: "Detrack", category: "Logistics" },
  { id: "dialmycalls", name: "DialMyCalls", category: "Communication" },
  { id: "dialpad", name: "Dialpad", category: "Communication" },
  { id: "dictionaryapi", name: "Dictionary API", category: "Data" },
  { id: "diffbot", name: "Diffbot", category: "AI" },
  { id: "digicert", name: "DigiCert", category: "Security" },
  { id: "digitalocean", name: "Digital Ocean", category: "Infrastructure" },
  { id: "discord", name: "Discord", category: "Communication" },
  { id: "discordbot", name: "Discord Bot", category: "Communication" },
  { id: "dnsfilter", name: "DNSFilter", category: "Security" },
  { id: "dockcerts", name: "Dock Certs", category: "Document" },
  { id: "dockerhub", name: "Docker Hub", category: "Development" },
  { id: "docmosis", name: "Docmosis", category: "Document" },
  { id: "docnify", name: "Docnify", category: "Document" },
  { id: "docsbotai", name: "DocsBot AI", category: "AI" },
  { id: "docsumo", name: "Docsumo", category: "AI" },
  { id: "docugenerate", name: "DocuGenerate", category: "Document" },
  { id: "documenso", name: "Documenso", category: "Document" },
  { id: "documint", name: "Documint", category: "Document" },
  { id: "docupilot", name: "Docupilot", category: "Document" },
  { id: "docupost", name: "DocuPost", category: "Document" },
  { id: "docuseal", name: "DocuSeal", category: "Document" },
  { id: "docusign", name: "DocuSign", category: "Document" },
  { id: "dopplermarketing", name: "Doppler Marketing", category: "Marketing" },
  { id: "dopplersecretops", name: "Doppler SecretOps", category: "Security" },
  { id: "dotsimple", name: "DotSimple", category: "Social Media" },
  { id: "dovetail", name: "Dovetail", category: "Research" },
  { id: "dpd2", name: "DPD2", category: "Shipping" },
  { id: "draftable", name: "Draftable", category: "Document" },
  { id: "dreamstudio", name: "DreamStudio", category: "AI" },
  { id: "dripjobs", name: "Drip Jobs", category: "CRM" },
  { id: "dripcel", name: "Dripcel", category: "Marketing" },
  { id: "dromo", name: "Dromo", category: "Data" },
  { id: "dropbox", name: "Dropbox", category: "Storage" },
  { id: "dropboxsign", name: "Dropbox Sign", category: "Document" },
  { id: "dropcontact", name: "Dropcontact", category: "Data" },
  { id: "dungeonfighteronline", name: "Dungeon Fighter Online", category: "Gaming" },
  { id: "dynamics365", name: "Dynamics 365", category: "CRM" },
  { id: "echtpost", name: "EchtPost", category: "Communication" },
  { id: "egnyte", name: "Egnyte", category: "Storage" },
  { id: "elasticsearch", name: "Elasticsearch", category: "Search" },
  { id: "elevenlabs", name: "ElevenLabs", category: "AI" },
  { id: "elorus", name: "Elorus", category: "Finance" },
  { id: "emailable", name: "Emailable", category: "Email" },
  { id: "emaillistverify", name: "EmailListVerify", category: "Email" },
  { id: "emailoctopus", name: "EmailOctopus", category: "Marketing" },
  { id: "emelia", name: "Emelia", category: "Sales" },
  { id: "encodian", name: "Encodian", category: "Document" },
  { id: "endorsal", name: "Endorsal", category: "Marketing" },
  { id: "enginemailer", name: "Enginemailer", category: "Marketing" },
  { id: "enigma", name: "Enigma", category: "Data" },
  { id: "entelligence", name: "Entelligence", category: "AI" },
  { id: "eodhd", name: "EODHD APIs", category: "Finance" },
  { id: "epicgames", name: "Epic Games", category: "Gaming" },
  { id: "esignaturesio", name: "eSignatures.io", category: "Document" },
  { id: "espocrm", name: "EspoCRM", category: "CRM" },
  { id: "esputnik", name: "eSputnik", category: "Marketing" },
  { id: "etermin", name: "eTermin", category: "Scheduling" },
  { id: "evenium", name: "Evenium", category: "Events" },
  { id: "eventbrite", name: "Eventbrite", category: "Events" },
  { id: "eventee", name: "Eventee", category: "Events" },
  { id: "eventzilla", name: "Eventzilla", category: "Events" },
  { id: "everhour", name: "Everhour", category: "Time Tracking" },
  { id: "eversign", name: "Eversign", category: "Document" },
  { id: "exa", name: "Exa", category: "Search" },
  { id: "excel", name: "Excel", category: "Productivity" },
  { id: "exist", name: "Exist", category: "Analytics" },
  { id: "expensify", name: "Expensify", category: "Finance" },
  { id: "expofp", name: "ExpoFP", category: "Events" },
  { id: "extractaai", name: "Extracta AI", category: "AI" },
  { id: "facebook", name: "Facebook", category: "Social Media" },
  { id: "faceup", name: "FaceUp", category: "Compliance" },
  { id: "factorial", name: "Factorial", category: "HR" },
  { id: "fathom", name: "Fathom", category: "AI" },
  { id: "feathery", name: "Feathery", category: "Forms" },
  { id: "felt", name: "Felt", category: "Maps" },
  { id: "fibery", name: "Fibery", category: "Project Management" },
  { id: "fidelapi", name: "Fidel API", category: "Finance" },
  { id: "figma", name: "Figma", category: "Creative" },
  { id: "filescom", name: "Files.com", category: "Storage" },
  { id: "filloutforms", name: "Fillout Forms", category: "Forms" },
  { id: "finage", name: "Finage", category: "Finance" },
  { id: "findymail", name: "Findymail", category: "Email" },
  { id: "finerworks", name: "FinerWorks", category: "Print" },
  { id: "fingertip", name: "Fingertip", category: "Business" },
  { id: "finmei", name: "Finmei", category: "Finance" },
  { id: "fireberry", name: "Fireberry", category: "CRM" },
  { id: "firecrawl", name: "Firecrawl", category: "Automation" },
  { id: "fireflies", name: "Fireflies", category: "AI" },
  { id: "firmao", name: "Firmao", category: "Data" },
  { id: "fitbit", name: "Fitbit", category: "Health" },
  { id: "fixer", name: "Fixer", category: "Finance" },
  { id: "fixerio", name: "Fixer.io", category: "Finance" },
  { id: "flexisign", name: "FlexiSign", category: "Document" },
  { id: "flowiseai", name: "FlowiseAI", category: "AI" },
  { id: "flutterwave", name: "Flutterwave", category: "Payments" },
  { id: "fluxguard", name: "Fluxguard", category: "Monitoring" },
  { id: "folk", name: "Folk", category: "CRM" },
  { id: "fomo", name: "Fomo", category: "Marketing" },
  { id: "forcemanager", name: "ForceManager", category: "CRM" },
  { id: "formbricks", name: "Formbricks", category: "Forms" },
  { id: "formcarry", name: "Formcarry", category: "Forms" },
  { id: "formdesk", name: "Formdesk", category: "Forms" },
  { id: "formsite", name: "Formsite", category: "Forms" },
  { id: "foursquare", name: "Foursquare", category: "Location" },
  { id: "fraudlabspro", name: "FraudLabs Pro", category: "Security" },
  { id: "freeagent", name: "FreeAgent", category: "Finance" },
  { id: "freshbooks", name: "FreshBooks", category: "Finance" },
  { id: "freshdesk", name: "Freshdesk", category: "Support" },
  { id: "freshservice", name: "Freshservice", category: "IT" },
  { id: "front", name: "Front", category: "Communication" },
  { id: "fullenrich", name: "FullEnrich", category: "Data" },
  { id: "gagelist", name: "GageList", category: "Quality" },
  { id: "gamma", name: "Gamma", category: "AI" },
  { id: "ganai", name: "Gan.AI", category: "AI" },
  { id: "gatherup", name: "GatherUp", category: "Marketing" },
  { id: "genderapi", name: "Gender API", category: "Data" },
  { id: "genderapiio", name: "GenderAPI.io", category: "Data" },
  { id: "genderize", name: "Genderize", category: "Data" },
  { id: "geoapify", name: "Geoapify", category: "Maps" },
  { id: "geocodio", name: "Geocodio", category: "Maps" },
  { id: "geokeo", name: "Geokeo", category: "Maps" },
  { id: "getform", name: "Getform", category: "Forms" },
  { id: "giftup", name: "Gift Up", category: "E-Commerce" },
  { id: "gigasheet", name: "Gigasheet", category: "Data" },
  { id: "giphy", name: "GIPHY", category: "Media" },
  { id: "gist", name: "Gist", category: "Development" },
  { id: "gitlab", name: "GitLab", category: "Development" },
  { id: "givebutter", name: "Givebutter", category: "Nonprofit" },
  { id: "gladia", name: "Gladia", category: "AI" },
  { id: "gleap", name: "Gleap", category: "Support" },
  { id: "globalping", name: "Globalping", category: "Infrastructure" },
  { id: "gotowebinar", name: "GoToWebinar", category: "Communication" },
  { id: "godial", name: "GoDial", category: "Communication" },
  { id: "gong", name: "Gong", category: "Sales" },
  { id: "goodbits", name: "Goodbits", category: "Marketing" },
  { id: "goody", name: "Goody", category: "Gifting" },
  { id: "googleaddressvalidation", name: "Google Address Validation", category: "Maps" },
  { id: "googleadmin", name: "Google Admin", category: "IT" },
  { id: "googleads", name: "Google Ads", category: "Advertising" },
  { id: "googleanalytics", name: "Google Analytics", category: "Analytics" },
  { id: "googlebigquery", name: "Google BigQuery", category: "Database" },
  { id: "gemini", name: "Gemini", category: "AI" },
  { id: "googlecalendar", name: "Google Calendar", category: "Scheduling" },
  { id: "googleclassroom", name: "Google Classroom", category: "Education" },
  { id: "googlecloudvision", name: "Google Cloud Vision", category: "AI" },
  { id: "googledocs", name: "Google Docs", category: "Productivity" },
  { id: "googlemaps", name: "Google Maps", category: "Maps" },
  { id: "googlemeet", name: "Google Meet", category: "Communication" },
  { id: "googlesearchconsole", name: "Google Search Console", category: "SEO" },
  { id: "googleslides", name: "Google Slides", category: "Productivity" },
  { id: "googlesuper", name: "Google Super", category: "Productivity" },
  { id: "googletasks", name: "Google Tasks", category: "Productivity" },
  { id: "googlephotos", name: "Google Photos", category: "Media" },
  { id: "gorgias", name: "Gorgias", category: "Support" },
  { id: "gosquared", name: "GoSquared", category: "Analytics" },
  { id: "grafbase", name: "Grafbase", category: "Development" },
  { id: "graphhopper", name: "GraphHopper", category: "Maps" },
  { id: "griptape", name: "Griptape", category: "AI" },
  { id: "grist", name: "Grist", category: "Database" },
  { id: "groqcloud", name: "GroqCloud", category: "AI" },
  { id: "gumroad", name: "Gumroad", category: "E-Commerce" },
  { id: "guru", name: "Guru", category: "Knowledge" },
  { id: "gusto", name: "Gusto", category: "HR" },
  { id: "habitica", name: "Habitica", category: "Productivity" },
  { id: "hackernews", name: "Hacker News", category: "News" },
  { id: "hackerrankwork", name: "HackerRank Work", category: "HR" },
  { id: "happyscribe", name: "Happy Scribe", category: "Media" },
  { id: "harvest", name: "Harvest", category: "Time Tracking" },
  { id: "hashnode", name: "Hashnode", category: "Development" },
  { id: "headout", name: "Headout", category: "Travel" },
  { id: "helcim", name: "Helcim", category: "Payments" },
  { id: "helloleads", name: "HelloLeads", category: "CRM" },
  { id: "helpdesk", name: "HelpDesk", category: "Support" },
  { id: "helpwise", name: "Helpwise", category: "Support" },
  { id: "here", name: "HERE", category: "Maps" },
  { id: "heygen", name: "HeyGen", category: "AI" },
  { id: "heyreach", name: "HeyReach", category: "Sales" },
  { id: "heyzine", name: "Heyzine", category: "Publishing" },
  { id: "highergov", name: "HigherGov", category: "Government" },
  { id: "highlevel", name: "HighLevel", category: "Marketing" },
  { id: "honeybadger", name: "Honeybadger", category: "Development" },
  { id: "honeyhive", name: "HoneyHive", category: "AI" },
  { id: "hookdeck", name: "Hookdeck", category: "Development" },
  { id: "hotspotsystem", name: "HotspotSystem", category: "Network" },
  { id: "htmltoimage", name: "HTML to Image", category: "Utilities" },
  { id: "humanitix", name: "Humanitix", category: "Events" },
  { id: "humanloop", name: "Humanloop", category: "AI" },
  { id: "hunter", name: "Hunter", category: "Email" },
  { id: "hypeauditor", name: "HypeAuditor", category: "Marketing" },
  { id: "hyperbrowser", name: "Hyperbrowser", category: "Automation" },
  { id: "hyperise", name: "Hyperise", category: "Marketing" },
  { id: "hystruct", name: "Hystruct", category: "AI" },
  { id: "icims", name: "iCIMS", category: "HR" },
  { id: "icypeas", name: "Icypeas", category: "Email" },
  { id: "ideascale", name: "IdeaScale", category: "Innovation" },
  { id: "identitycheck", name: "IdentityCheck", category: "Security" },
  { id: "ignisign", name: "IgniSign", category: "Document" },
  { id: "imagekitio", name: "ImageKit.io", category: "Media" },
  { id: "imagior", name: "Imagior", category: "AI" },
  { id: "imejisio", name: "Imejis.io", category: "Creative" },
  { id: "imgbb", name: "ImgBB", category: "Media" },
  { id: "imgix", name: "imgix", category: "Media" },
  { id: "influxdb", name: "InfluxDB Cloud", category: "Database" },
  { id: "insightoai", name: "Insighto AI", category: "AI" },
  { id: "instacart", name: "Instacart", category: "E-Commerce" },
  { id: "instagram", name: "Instagram", category: "Social Media" },
  { id: "instantly", name: "Instantly", category: "Email" },
  { id: "intelliprint", name: "Intelliprint", category: "Print" },
  { id: "intercom", name: "Intercom", category: "Support" },
  { id: "interzoid", name: "Interzoid", category: "Data" },
  { id: "ip2location", name: "IP2Location", category: "Data" },
  { id: "ip2locationio", name: "IP2Location.io", category: "Data" },
  { id: "ip2proxy", name: "IP2Proxy", category: "Security" },
  { id: "ip2whois", name: "IP2WHOIS", category: "Data" },
  { id: "ipdataco", name: "ipdata.co", category: "Data" },
  { id: "ipinfotio", name: "IPinfo.io", category: "Data" },
  { id: "iqairvisual", name: "IQAir AirVisual", category: "Data" },
  { id: "jigsawstack", name: "JigsawStack", category: "AI" },
  { id: "jira", name: "Jira", category: "Project Management" },
  { id: "jobnimbus", name: "JobNimbus", category: "CRM" },
  { id: "jotform", name: "Jotform", category: "Forms" },
  { id: "jumpcloud", name: "JumpCloud", category: "IT" },
  { id: "junglescout", name: "Jungle Scout", category: "E-Commerce" },
  { id: "kadoa", name: "Kadoa", category: "AI" },
  { id: "kaggle", name: "Kaggle", category: "Data Science" },
  { id: "kaleido", name: "Kaleido", category: "Blockchain" },
  { id: "keap", name: "Keap", category: "CRM" },
  { id: "keenio", name: "Keen.io", category: "Analytics" },
  { id: "kibana", name: "Kibana", category: "Analytics" },
  { id: "kickbox", name: "Kickbox", category: "Email" },
  { id: "kit", name: "Kit", category: "Marketing" },
  { id: "klaviyo", name: "Klaviyo", category: "Marketing" },
  { id: "klipfolio", name: "Klipfolio", category: "Analytics" },
  { id: "kofi", name: "Ko-fi", category: "Payments" },
  { id: "kommo", name: "Kommo", category: "CRM" },
  { id: "kontentai", name: "Kontent.ai", category: "CMS" },
  { id: "krakenio", name: "Kraken.io", category: "Media" },
  { id: "l2s", name: "L2S", category: "Utilities" },
  { id: "labs64netlicensing", name: "Labs64 NetLicensing", category: "Licensing" },
  { id: "landbot", name: "Landbot", category: "AI" },
  { id: "langbase", name: "Langbase", category: "AI" },
  { id: "lastpass", name: "LastPass", category: "Security" },
  { id: "launchdarkly", name: "LaunchDarkly", category: "Development" },
  { id: "leadfeeder", name: "Leadfeeder", category: "Sales" },
  { id: "leadoku", name: "Leadoku", category: "Sales" },
  { id: "leiga", name: "Leiga", category: "Project Management" },
  { id: "lemlist", name: "Lemlist", category: "Sales" },
  { id: "lemonsqueezy", name: "Lemon Squeezy", category: "Payments" },
  { id: "lessonspace", name: "Lessonspace", category: "Education" },
  { id: "lever", name: "Lever", category: "HR" },
  { id: "leverly", name: "Leverly", category: "Sales" },
  { id: "lexoffice", name: "Lexoffice", category: "Finance" },
  { id: "linear", name: "Linear", category: "Project Management" },
  { id: "linguapop", name: "Linguapop", category: "Education" },
  { id: "linkedin", name: "LinkedIn", category: "Social Media" },
  { id: "linkhut", name: "LinkHut", category: "Bookmarks" },
  { id: "linkup", name: "Linkup", category: "Search" },
  { id: "listclean", name: "Listclean", category: "Email" },
  { id: "listennotes", name: "Listen Notes", category: "Media" },
  { id: "livesession", name: "LiveSession", category: "Analytics" },
  { id: "lmnt", name: "LMNT", category: "AI" },
  { id: "lodgify", name: "Lodgify", category: "Hospitality" },
  { id: "logodev", name: "Logo.dev", category: "Data" },
  { id: "loomio", name: "Loomio", category: "Collaboration" },
  { id: "loyverse", name: "Loyverse", category: "POS" },
  { id: "magnetic", name: "Magnetic", category: "Project Management" },
  { id: "mailbluster", name: "MailBluster", category: "Marketing" },
  { id: "mailboxlayer", name: "Mailboxlayer", category: "Email" },
  { id: "mailcheck", name: "Mailcheck", category: "Email" },
  { id: "mailchimp", name: "Mailchimp", category: "Marketing" },
  { id: "mailcoach", name: "Mailcoach", category: "Marketing" },
  { id: "mailerlite", name: "MailerLite", category: "Marketing" },
  { id: "mailersend", name: "MailerSend", category: "Email" },
  { id: "mailsso", name: "Mails.so", category: "Email" },
  { id: "mailsoftly", name: "Mailsoftly", category: "Marketing" },
  { id: "maintainx", name: "MaintainX", category: "Maintenance" },
  { id: "make", name: "Make", category: "Automation" },
  { id: "manychat", name: "ManyChat", category: "Marketing" },
  { id: "mapbox", name: "Mapbox", category: "Maps" },
  { id: "mapulus", name: "Mapulus", category: "Maps" },
  { id: "mboum", name: "Mboum", category: "Finance" },
  { id: "melo", name: "Melo", category: "Real Estate" },
  { id: "mem", name: "Mem", category: "Productivity" },
  { id: "mem0", name: "Mem0", category: "AI" },
  { id: "memberspot", name: "Memberspot", category: "Education" },
  { id: "memberstack", name: "Memberstack", category: "Development" },
  { id: "membervault", name: "MemberVault", category: "E-Commerce" },
  { id: "metaads", name: "Meta Ads", category: "Advertising" },
  { id: "metaphor", name: "Metaphor", category: "Search" },
  { id: "metatextai", name: "Metatext AI", category: "AI" },
  { id: "mezmo", name: "Mezmo", category: "Logging" },
  { id: "microsoftclarity", name: "Microsoft Clarity", category: "Analytics" },
  { id: "microsoftteams", name: "Microsoft Teams", category: "Communication" },
  { id: "microsofttenant", name: "Microsoft Tenant", category: "IT" },
  { id: "minerstat", name: "minerstat", category: "Blockchain" },
  { id: "miro", name: "Miro", category: "Collaboration" },
  { id: "missive", name: "Missive", category: "Communication" },
  { id: "mistralai", name: "Mistral AI", category: "AI" },
  { id: "mixpanel", name: "Mixpanel", category: "Analytics" },
  { id: "mocean", name: "Mocean", category: "Communication" },
  { id: "moco", name: "MOCO", category: "Project Management" },
  { id: "modelry", name: "Modelry", category: "AI" },
  { id: "monday", name: "Monday", category: "Project Management" },
  { id: "moneybird", name: "Moneybird", category: "Finance" },
  { id: "moonclerk", name: "MoonClerk", category: "Payments" },
  { id: "moosend", name: "Moosend", category: "Marketing" },
  { id: "mopinion", name: "Mopinion", category: "Feedback" },
  { id: "moretrees", name: "More Trees", category: "Sustainability" },
  { id: "moxie", name: "Moxie", category: "Business" },
  { id: "moz", name: "Moz", category: "SEO" },
  { id: "msg91", name: "MSG91", category: "Communication" },
  { id: "mural", name: "Mural", category: "Collaboration" },
  { id: "mxtechnologies", name: "MX Technologies", category: "Finance" },
  { id: "mxtoolbox", name: "MX Toolbox", category: "Email" },
  { id: "nango", name: "Nango", category: "Development" },
  { id: "nanonets", name: "Nanonets", category: "AI" },
  { id: "nasa", name: "NASA", category: "Data" },
  { id: "nasdaq", name: "Nasdaq", category: "Finance" },
  { id: "ncscale", name: "NCScale", category: "Analytics" },
  { id: "needle", name: "Needle", category: "AI" },
  { id: "neon", name: "Neon", category: "Database" },
  { id: "netsuite", name: "NetSuite", category: "ERP" },
  { id: "neuronwriter", name: "NeuronWriter", category: "SEO" },
  { id: "neutrino", name: "Neutrino", category: "Utilities" },
  { id: "neverbounce", name: "NeverBounce", category: "Email" },
  { id: "newrelic", name: "New Relic", category: "Development" },
  { id: "newsapi", name: "News API", category: "News" },
  { id: "nextdns", name: "NextDNS", category: "Security" },
  { id: "ngrok", name: "Ngrok", category: "Development" },
  { id: "ninox", name: "Ninox", category: "Database" },
  { id: "nocrmio", name: "noCRM.io", category: "CRM" },
  { id: "npm", name: "npm", category: "Development" },
  { id: "ocrwebservice", name: "OCR Web Service", category: "AI" },
  { id: "ocrspace", name: "OCR.space", category: "AI" },
  { id: "omnisend", name: "Omnisend", category: "Marketing" },
  { id: "oncehub", name: "OnceHub", category: "Scheduling" },
  { id: "onedrive", name: "OneDrive", category: "Storage" },
  { id: "onedesk", name: "OneDesk", category: "Project Management" },
  { id: "onepage", name: "OnePage", category: "Data" },
  { id: "onesignal", name: "OneSignal", category: "Communication" },
  { id: "opensea", name: "OpenSea", category: "Blockchain" },
  { id: "openai", name: "OpenAI", category: "AI" },
  { id: "opencage", name: "OpenCage", category: "Maps" },
  { id: "opengraphio", name: "OpenGraph.io", category: "Data" },
  { id: "openperplex", name: "Openperplex", category: "AI" },
  { id: "openrouter", name: "OpenRouter", category: "AI" },
  { id: "openweatherapi", name: "OpenWeather API", category: "Weather" },
  { id: "optimoroute", name: "OptimoRoute", category: "Logistics" },
  { id: "outlook", name: "Outlook", category: "Communication" },
  { id: "owlprotocol", name: "Owl Protocol", category: "Blockchain" },
  { id: "oysterhr", name: "OysterHR", category: "HR" },
  { id: "pagex", name: "PAGE X", category: "CRM" },
  { id: "pagerduty", name: "PagerDuty", category: "IT" },
  { id: "pandadoc", name: "PandaDoc", category: "Document" },
  { id: "paradym", name: "Paradym", category: "Identity" },
  { id: "parallel", name: "Parallel", category: "AI" },
  { id: "parma", name: "Parma", category: "CRM" },
  { id: "parsehub", name: "ParseHub", category: "Automation" },
  { id: "parsera", name: "Parsera", category: "AI" },
  { id: "parseur", name: "Parseur", category: "AI" },
  { id: "passcreator", name: "Passcreator", category: "Marketing" },
  { id: "passslot", name: "PassSlot", category: "Marketing" },
  { id: "payhip", name: "Payhip", category: "E-Commerce" },
  { id: "pdfapiio", name: "PDF-API.io", category: "Document" },
  { id: "pdfco", name: "PDF.co", category: "Document" },
  { id: "pdf4me", name: "PDF4me", category: "Document" },
  { id: "pdfless", name: "Pdfless", category: "Document" },
  { id: "pdfmonkey", name: "PDFMonkey", category: "Document" },
  { id: "peopledatalabs", name: "People Data Labs", category: "Data" },
  { id: "perigon", name: "Perigon", category: "News" },
  { id: "perplexityai", name: "Perplexity AI", category: "AI" },
  { id: "persistiq", name: "PersistIQ", category: "Sales" },
  { id: "pexels", name: "Pexels", category: "Media" },
  { id: "phantombuster", name: "PhantomBuster", category: "Automation" },
  { id: "piggy", name: "Piggy", category: "Loyalty" },
  { id: "piloterr", name: "Piloterr", category: "Data" },
  { id: "pilvio", name: "Pilvio", category: "Infrastructure" },
  { id: "pingdom", name: "Pingdom", category: "Monitoring" },
  { id: "pipedrive", name: "Pipedrive", category: "CRM" },
  { id: "pipelinecrm", name: "Pipeline CRM", category: "CRM" },
  { id: "placekey", name: "Placekey", category: "Location" },
  { id: "placid", name: "Placid", category: "Creative" },
  { id: "plain", name: "Plain", category: "Support" },
  { id: "plasmic", name: "Plasmic", category: "Development" },
  { id: "platerecognizer", name: "Plate Recognizer", category: "AI" },
  { id: "plisio", name: "Plisio", category: "Payments" },
  { id: "polygon", name: "Polygon", category: "Finance" },
  { id: "polygonio", name: "Polygon.io", category: "Finance" },
  { id: "poptin", name: "Poptin", category: "Marketing" },
  { id: "postgrid", name: "PostGrid", category: "Print" },
  { id: "posthog", name: "PostHog", category: "Analytics" },
  { id: "postmark", name: "Postmark", category: "Email" },
  { id: "precoro", name: "Precoro", category: "Procurement" },
  { id: "prerender", name: "Prerender", category: "SEO" },
  { id: "printautopilot", name: "Print Autopilot", category: "Print" },
  { id: "printnode", name: "PrintNode", category: "Print" },
  { id: "prisma", name: "Prisma", category: "Database" },
  { id: "prismic", name: "Prismic", category: "CMS" },
  { id: "processstreet", name: "Process Street", category: "Process" },
  { id: "procfu", name: "ProcFu", category: "Automation" },
  { id: "productboard", name: "Productboard", category: "Product" },
  { id: "productlane", name: "Productlane", category: "Support" },
  { id: "projectbubble", name: "Project Bubble", category: "Project Management" },
  { id: "promptmateio", name: "Promptmate.io", category: "AI" },
  { id: "proofly", name: "Proofly", category: "Marketing" },
  { id: "proxiedmail", name: "ProxiedMail", category: "Privacy" },
  { id: "pushbullet", name: "Pushbullet", category: "Communication" },
  { id: "pushover", name: "Pushover", category: "Communication" },
  { id: "quaderno", name: "Quaderno", category: "Finance" },
  { id: "qualaroo", name: "Qualaroo", category: "Feedback" },
  { id: "quickbooks", name: "QuickBooks", category: "Finance" },
  { id: "radar", name: "Radar", category: "Location" },
  { id: "rafflys", name: "Rafflys", category: "Marketing" },
  { id: "ragic", name: "Ragic", category: "Database" },
  { id: "raisely", name: "Raisely", category: "Nonprofit" },
  { id: "rakuten", name: "Rakuten", category: "E-Commerce" },
  { id: "ramp", name: "Ramp", category: "Finance" },
  { id: "ravenseotools", name: "Raven SEO Tools", category: "SEO" },
  { id: "reamaze", name: "Re:amaze", category: "Support" },
  { id: "realphonevalidation", name: "RealPhoneValidation", category: "Data" },
  { id: "recallai", name: "Recall AI", category: "AI" },
  { id: "recruitee", name: "Recruitee", category: "HR" },
  { id: "reddit", name: "Reddit", category: "Social Media" },
  { id: "refiner", name: "Refiner", category: "Feedback" },
  { id: "remarkety", name: "Remarkety", category: "Marketing" },
  { id: "remoteretrieval", name: "Remote Retrieval", category: "IT" },
  { id: "removebg", name: "Remove.bg", category: "AI" },
  { id: "render", name: "Render", category: "Infrastructure" },
  { id: "renderform", name: "RenderForm", category: "Creative" },
  { id: "repairshopr", name: "RepairShopr", category: "Business" },
  { id: "replicate", name: "Replicate", category: "AI" },
  { id: "reply", name: "Reply", category: "Sales" },
  { id: "replyio", name: "Reply.io", category: "Sales" },
  { id: "resend", name: "Resend", category: "Email" },
  { id: "respondio", name: "Respond.io", category: "Communication" },
  { id: "retailed", name: "Retailed", category: "E-Commerce" },
  { id: "retellai", name: "Retell AI", category: "AI" },
  { id: "retently", name: "Retently", category: "Feedback" },
  { id: "revai", name: "Rev AI", category: "AI" },
  { id: "revolt", name: "Revolt", category: "Communication" },
  { id: "ringcentral", name: "RingCentral", category: "Communication" },
  { id: "rippling", name: "Rippling", category: "HR" },
  { id: "ritekit", name: "RiteKit", category: "Social Media" },
  { id: "rkvst", name: "RKVST", category: "Security" },
  { id: "rocketreach", name: "RocketReach", category: "Data" },
  { id: "rocketlane", name: "Rocketlane", category: "Project Management" },
  { id: "rootly", name: "Rootly", category: "IT" },
  { id: "rosettetextanalytics", name: "Rosette Text Analytics", category: "AI" },
  { id: "route4me", name: "Route4Me", category: "Logistics" },
  { id: "safetyculture", name: "SafetyCulture", category: "Safety" },
  { id: "sage", name: "Sage", category: "Finance" },
  { id: "salesflare", name: "Salesflare", category: "CRM" },
  { id: "salesforce", name: "Salesforce", category: "CRM" },
  { id: "salesforcemarketingcloud", name: "Salesforce Marketing Cloud", category: "Marketing" },
  { id: "salesforceservicecloud", name: "Salesforce Service Cloud", category: "Support" },
  { id: "salesmate", name: "Salesmate", category: "CRM" },
  { id: "sapsuccessfactors", name: "SAP SuccessFactors", category: "HR" },
  { id: "satismeter", name: "SatisMeter", category: "Feedback" },
  { id: "scrapedo", name: "Scrape.do", category: "Automation" },
  { id: "scrapegraphai", name: "ScrapeGraph AI", category: "AI" },
  { id: "scrapfly", name: "Scrapfly", category: "Automation" },
  { id: "scrapingant", name: "ScrapingAnt", category: "Automation" },
  { id: "scrapingbee", name: "ScrapingBee", category: "Automation" },
  { id: "screenshotfyi", name: "Screenshot.fyi", category: "Utilities" },
  { id: "screenshotone", name: "ScreenshotOne", category: "Utilities" },
  { id: "seatgeek", name: "SeatGeek", category: "Events" },
  { id: "securitytrails", name: "SecurityTrails", category: "Security" },
  { id: "segment", name: "Segment", category: "Analytics" },
  { id: "segmetrics", name: "SegMetrics", category: "Analytics" },
  { id: "seismic", name: "Seismic", category: "Sales" },
  { id: "semanticscholar", name: "Semantic Scholar", category: "Research" },
  { id: "semrush", name: "SEMrush", category: "SEO" },
  { id: "sendbird", name: "Sendbird", category: "Communication" },
  { id: "sendbirdaichatbot", name: "Sendbird AI Chatbot", category: "AI" },
  { id: "sendfox", name: "SendFox", category: "Marketing" },
  { id: "sendgrid", name: "SendGrid", category: "Email" },
  { id: "sendlane", name: "Sendlane", category: "Marketing" },
  { id: "sendloop", name: "Sendloop", category: "Marketing" },
  { id: "sendspark", name: "Sendspark", category: "Sales" },
  { id: "sensibo", name: "Sensibo", category: "Smart Home" },
  { id: "sentry", name: "Sentry", category: "Development" },
  { id: "seqera", name: "Seqera", category: "Science" },
  { id: "serpapi", name: "SerpAPI", category: "Search" },
  { id: "serpdog", name: "Serpdog", category: "Search" },
  { id: "serply", name: "Serply", category: "Search" },
  { id: "servicem8", name: "ServiceM8", category: "Field Service" },
  { id: "servicenow", name: "ServiceNow", category: "IT" },
  { id: "sevdesk", name: "sevDesk", category: "Finance" },
  { id: "sharepoint", name: "SharePoint", category: "Storage" },
  { id: "shipengine", name: "ShipEngine", category: "Shipping" },
  { id: "shortio", name: "Short.io", category: "Utilities" },
  { id: "shortmenu", name: "Short Menu", category: "Utilities" },
  { id: "shortcut", name: "Shortcut", category: "Project Management" },
  { id: "shortenrest", name: "Shorten.REST", category: "Utilities" },
  { id: "shortpixel", name: "ShortPixel", category: "Media" },
  { id: "shotstack", name: "Shotstack", category: "Media" },
  { id: "sidetracker", name: "Sidetracker", category: "Analytics" },
  { id: "signaturely", name: "Signaturely", category: "Document" },
  { id: "signpath", name: "SignPath", category: "Security" },
  { id: "signwell", name: "SignWell", category: "Document" },
  { id: "similarweb", name: "Similarweb", category: "Analytics" },
  { id: "simlacom", name: "Simla.com", category: "CRM" },
  { id: "simpleanalytics", name: "Simple Analytics", category: "Analytics" },
  { id: "simplesat", name: "Simplesat", category: "Feedback" },
  { id: "sitespeakai", name: "SiteSpeakAI", category: "AI" },
  { id: "skyfire", name: "Skyfire", category: "Payments" },
  { id: "slackbot", name: "Slackbot", category: "Communication" },
  { id: "smartproxy", name: "Smartproxy", category: "Data" },
  { id: "smartrecruiters", name: "SmartRecruiters", category: "HR" },
  { id: "smsalert", name: "SMS Alert", category: "Communication" },
  { id: "smtp2go", name: "SMTP2GO", category: "Email" },
  { id: "smugmug", name: "SmugMug", category: "Media" },
  { id: "snowflake", name: "Snowflake", category: "Database" },
  { id: "sourcegraph", name: "Sourcegraph", category: "Development" },
  { id: "splitwise", name: "Splitwise", category: "Finance" },
  { id: "spoki", name: "Spoki", category: "Communication" },
  { id: "spondyr", name: "Spondyr", category: "Communication" },
  { id: "spotify", name: "Spotify", category: "Media" },
  { id: "spotlightr", name: "Spotlightr", category: "Media" },
  { id: "square", name: "Square", category: "Payments" },
  { id: "sslmatecertspotter", name: "SSLMate Cert Spotter", category: "Security" },
  { id: "stackexchange", name: "Stack Exchange", category: "Q&A" },
  { id: "stannp", name: "Stannp", category: "Print" },
  { id: "starton", name: "Starton", category: "Blockchain" },
  { id: "statuscake", name: "StatusCake", category: "Monitoring" },
  { id: "storeganise", name: "Storeganise", category: "Storage" },
  { id: "storerocket", name: "StoreRocket", category: "Location" },
  { id: "stormglassio", name: "stormglass.io", category: "Weather" },
  { id: "strava", name: "Strava", category: "Health" },
  { id: "streamtime", name: "Streamtime", category: "Project Management" },
  { id: "stripe", name: "Stripe", category: "Payments" },
  { id: "supadata", name: "Supadata", category: "Data" },
  { id: "superchat", name: "Superchat", category: "Communication" },
  { id: "supportbee", name: "SupportBee", category: "Support" },
  { id: "supportivekoala", name: "Supportivekoala", category: "Creative" },
  { id: "surveymonkey", name: "SurveyMonkey", category: "Survey" },
  { id: "svix", name: "Svix", category: "Development" },
  { id: "sympla", name: "Sympla", category: "Events" },
  { id: "synthflowai", name: "Synthflow AI", category: "AI" },
  { id: "taggun", name: "Taggun", category: "AI" },
  { id: "talenthr", name: "TalentHR", category: "HR" },
  { id: "tally", name: "Tally", category: "Forms" },
  { id: "tapfiliate", name: "Tapfiliate", category: "Affiliate" },
  { id: "tapform", name: "Tapform", category: "Forms" },
  { id: "tavily", name: "Tavily", category: "Search" },
  { id: "taxjar", name: "TaxJar", category: "Finance" },
  { id: "teamcamp", name: "Teamcamp", category: "Project Management" },
  { id: "teamleader", name: "Teamleader", category: "CRM" },
  { id: "telegram", name: "Telegram", category: "Communication" },
  { id: "telnyx", name: "Telnyx", category: "Communication" },
  { id: "teltel", name: "TelTel", category: "Communication" },
  { id: "templated", name: "Templated", category: "Creative" },
  { id: "terminus", name: "Terminus", category: "Marketing" },
  { id: "testapp", name: "Test App", category: "Testing" },
  { id: "texttopdf", name: "Text to PDF", category: "Utilities" },
  { id: "textcortex", name: "TextCortex", category: "AI" },
  { id: "textit", name: "TextIt", category: "Communication" },
  { id: "textrazor", name: "TextRazor", category: "AI" },
  { id: "thanksio", name: "thanks.io", category: "Print" },
  { id: "theoddsapi", name: "The Odds API", category: "Sports" },
  { id: "ticketmaster", name: "Ticketmaster", category: "Events" },
  { id: "ticktick", name: "TickTick", category: "Productivity" },
  { id: "tiktok", name: "TikTok", category: "Social Media" },
  { id: "timecamp", name: "TimeCamp", category: "Time Tracking" },
  { id: "timekit", name: "Timekit", category: "Scheduling" },
  { id: "timelinesai", name: "TimelinesAI", category: "Communication" },
  { id: "timelink", name: "Timelink", category: "Time Tracking" },
  { id: "timely", name: "Timely", category: "Time Tracking" },
  { id: "tinypng", name: "TinyPNG", category: "Media" },
  { id: "tinyurl", name: "TinyURL", category: "Utilities" },
  { id: "tisane", name: "Tisane", category: "AI" },
  { id: "todoist", name: "Todoist", category: "Productivity" },
  { id: "toggl", name: "Toggl", category: "Time Tracking" },
  { id: "tokenmetrics", name: "Token Metrics", category: "Blockchain" },
  { id: "tomba", name: "Tomba", category: "Email" },
  { id: "tomtom", name: "TomTom", category: "Maps" },
  { id: "toneden", name: "ToneDen", category: "Marketing" },
  { id: "tpscheck", name: "TPSCheck", category: "Compliance" },
  { id: "trello", name: "Trello", category: "Project Management" },
  { id: "triggercmd", name: "TRIGGERcmd", category: "Automation" },
  { id: "tripadvisor", name: "TripAdvisor", category: "Travel" },
  { id: "turbotpipes", name: "Turbot Pipes", category: "DevOps" },
  { id: "turso", name: "Turso", category: "Database" },
  { id: "twelvedata", name: "Twelve Data", category: "Finance" },
  { id: "twitch", name: "Twitch", category: "Media" },
  { id: "twitter", name: "Twitter", category: "Social Media" },
  { id: "twocaptcha", name: "2Captcha", category: "Automation" },
  { id: "typefully", name: "Typefully", category: "Social Media" },
  { id: "typless", name: "Typless", category: "AI" },
  { id: "u301", name: "U301", category: "Utilities" },
  { id: "unione", name: "UniOne", category: "Email" },
  { id: "updownio", name: "updown.io", category: "Monitoring" },
  { id: "uploadcare", name: "Uploadcare", category: "Media" },
  { id: "uptimerobot", name: "UptimeRobot", category: "Monitoring" },
  { id: "userlist", name: "Userlist", category: "Marketing" },
  { id: "v0", name: "v0", category: "AI" },
  { id: "venly", name: "Venly", category: "Blockchain" },
  { id: "veo", name: "Veo", category: "AI" },
  { id: "vercel", name: "Vercel", category: "Infrastructure" },
  { id: "verifiedemail", name: "VerifiedEmail", category: "Email" },
  { id: "veriphone", name: "Veriphone", category: "Data" },
  { id: "vero", name: "Vero", category: "Marketing" },
  { id: "vestaboard", name: "Vestaboard", category: "Hardware" },
  { id: "virustotal", name: "VirusTotal", category: "Security" },
  { id: "visme", name: "Visme", category: "Creative" },
  { id: "waboxapp", name: "Waboxapp", category: "Communication" },
  { id: "wachete", name: "Wachete", category: "Monitoring" },
  { id: "waiverfile", name: "WaiverFile", category: "Document" },
  { id: "wakatime", name: "WakaTime", category: "Development" },
  { id: "walgreens", name: "Walgreens", category: "E-Commerce" },
  { id: "wati", name: "Wati", category: "Communication" },
  { id: "waveaccounting", name: "Wave Accounting", category: "Finance" },
  { id: "weathermap", name: "WeatherMap", category: "Weather" },
  { id: "webex", name: "Webex", category: "Communication" },
  { id: "webflow", name: "Webflow", category: "Development" },
  { id: "webscrapingai", name: "WebScraping.AI", category: "Automation" },
  { id: "webvizio", name: "Webvizio", category: "Feedback" },
  { id: "whatsapp", name: "WhatsApp", category: "Communication" },
  { id: "whautomate", name: "Whautomate", category: "Communication" },
  { id: "winstonai", name: "Winston AI", category: "AI" },
  { id: "witai", name: "Wit.ai", category: "AI" },
  { id: "wix", name: "Wix", category: "Development" },
  { id: "wiz", name: "Wiz", category: "Security" },
  { id: "wolframalphaapi", name: "Wolfram Alpha API", category: "Data" },
  { id: "woodpeckerco", name: "Woodpecker.co", category: "Sales" },
  { id: "workable", name: "Workable", category: "HR" },
  { id: "workday", name: "Workday", category: "HR" },
  { id: "workiom", name: "Workiom", category: "Automation" },
  { id: "worksnaps", name: "Worksnaps", category: "Time Tracking" },
  { id: "wrike", name: "Wrike", category: "Project Management" },
  { id: "writer", name: "Writer", category: "AI" },
  { id: "xero", name: "Xero", category: "Finance" },
  { id: "ygy", name: "y.gy", category: "Utilities" },
  { id: "yandex", name: "Yandex", category: "Search" },
  { id: "yelp", name: "Yelp", category: "Local" },
  { id: "ynab", name: "YNAB", category: "Finance" },
  { id: "yousearch", name: "YouSearch", category: "Search" },
  { id: "youtube", name: "YouTube", category: "Media" },
  { id: "zendesk", name: "Zendesk", category: "Support" },
  { id: "zenrows", name: "ZenRows", category: "Automation" },
  { id: "zenserp", name: "Zenserp", category: "Search" },
  { id: "zeplin", name: "Zeplin", category: "Creative" },
  { id: "zerobounce", name: "ZeroBounce", category: "Email" },
  { id: "zoho", name: "Zoho", category: "CRM" },
  { id: "zohobigin", name: "Zoho Bigin", category: "CRM" },
  { id: "zohobooks", name: "Zoho Books", category: "Finance" },
  { id: "zohodesk", name: "Zoho Desk", category: "Support" },
  { id: "zohoinventory", name: "Zoho Inventory", category: "Inventory" },
  { id: "zohoinvoice", name: "Zoho Invoice", category: "Finance" },
  { id: "zohomail", name: "Zoho Mail", category: "Communication" },
  { id: "zoom", name: "Zoom", category: "Communication" },
  { id: "zoominfo", name: "ZoomInfo", category: "Data" },
  { id: "zylvie", name: "Zylvie", category: "E-Commerce" },
  { id: "zyteapi", name: "Zyte API", category: "Automation" },
];

const CATEGORIES = Array.from(new Set(ALL_TOOLKITS.map(t => t.category))).sort();

// Simple in-memory cache for connected accounts (User ID -> { slugs: string[], timestamp: number })
const connectedAccountsCache: Record<string, { slugs: string[], timestamp: number }> = {};
const CACHE_TTL = 60 * 1000; // 1 minute

export async function GET(request: Request) {
  const { searchParams } = new URL(request.url);
  const search = searchParams.get("search")?.toLowerCase() || "";
  const category = searchParams.get("category") || "";
  const limit = parseInt(searchParams.get("limit") || "50");
  const offset = parseInt(searchParams.get("offset") || "0");
  const userId = searchParams.get("userId");

  // 1. Fetch connected accounts (with caching)
  let connectedSlugs: string[] = [];
  
  if (userId) {
    const cached = connectedAccountsCache[userId];
    if (cached && (Date.now() - cached.timestamp < CACHE_TTL)) {
      connectedSlugs = cached.slugs;
    } else {
      try {
        const response = await getComposio().connectedAccounts.list({ userIds: [userId] });
        connectedSlugs = (response?.items || [])
          .filter((a: any) => a.status === "ACTIVE")
          .map((a: any) => a.toolkit?.slug?.toLowerCase())
          .filter(Boolean);
        
        // Update cache
        connectedAccountsCache[userId] = {
          slugs: connectedSlugs,
          timestamp: Date.now()
        };
      } catch (e) {
        console.error("Failed to fetch connected accounts for marketplace:", e);
      }
    }
  }

  let filtered = ALL_TOOLKITS;

  if (search) {
    filtered = filtered.filter(t => 
      t.name.toLowerCase().includes(search) || 
      t.id.toLowerCase().includes(search) ||
      t.category.toLowerCase().includes(search)
    );
  }

  if (category) {
    filtered = filtered.filter(t => t.category === category);
  }

  const total = filtered.length;
  // Apply connection status during mapping, effectively "joining" with the cached data
  const toolkits = filtered.slice(offset, offset + limit).map(t => ({
    ...t,
    logo: `https://logos.composio.dev/api/${t.id}`,
    marketplaceUrl: `https://rube.app/marketplace/${t.id}`,
    description: (t as any).description || `Automate tasks and workflows using ${t.name} with AI.`,
    connected: connectedSlugs.includes(t.id.toLowerCase()),
  }));

  return NextResponse.json({
    toolkits: toolkits, // already has connected status
    categories: CATEGORIES,
    total,
    hasMore: offset + limit < total,
  });
}